fail-on-severity: critical
allow-licenses:
  - MIT
  - ISC
  - BSD-2-Clause
  - BSD-3-Clause
  - Apache-2.0
  - 0BSD
  - Unlicense
  - CC0-1.0
  - (MIT AND Zlib)
  - (MIT OR Apache-2.0)
  - BlueOak-1.0.0
  - Python-2.0
deny-licenses: []
comment-summary-in-pr: true
license-check: false
vulnerability-check: true
allow-dependencies-licenses: []
